name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload aar
      uses: actions/upload-artifact@v4
      with:
        name: aars
        path: app/build/outputs/aar/

    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: app/build/outputs/apk/


